build:
	@env 'RUSTFLAGS=-C link-arg=-s' cargo +stable build --target wasm32-unknown-unknown --release


# init:
# near call gold.$NEAR_BASE_ACCOUNT new '{"owner_id": "nearswap.testnet", "total_supply": "1000000"}' --accountId $NEAR_BASE_ACCOUNT
#
