[package]
name = "nearswap"
version = "0.1.0"
authors = ["Robert Zaremba https://zaremba.ch"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", tag="3.0.0" }
uint = { version = "0.8.5", default-features = false }

[dev-dependencies]
#required for integration tests (simulation)
lazy_static = "1.4.0"
log = "0.4"
env_logger = { version = "0.7.1", default-features = false }
near-primitives = { git = "https://github.com/nearprotocol/nearcore.git" }
funty = "=1.1.0"
#New version of simulation tests:
# [dev-dependencies]
near-sdk-sim = { git = "https://github.com/near/near-sdk-rs.git", tag="3.0.0" }
nep21-mintable = { path = "../other-contracts/nep-21" }

# https://github.com/near/core-contracts/blob/master/staking-pool/Cargo.toml
# https://doc.rust-lang.org/cargo/reference/profiles.html

# compilation profile for a release target
[profile.release]
codegen-units = 1
# s = optimize for binary size ("z" would additionally turn off loop vectorization)
opt-level = "s"
# link time optimization
lto = true
debug = false
panic = "abort"
overflow-checks = true
