[package]
name = "nearswap"
version = "0.1.0"
authors = ["Robert Zaremba https://zaremba.ch"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", rev="b8c8589" } # tag="contract_cache_v0"
uint = { version = "0.8.5", default-features = false }

[dev-dependencies]
#required for integration tests (simulation)
lazy_static = "1.4.0"
log = "0.4"
env_logger = { version = "0.7.1", default-features = false }
near-primitives = { git = "https://github.com/nearprotocol/nearcore.git" }
funty = "=1.1.0"
near-sdk-sim = { git = "https://github.com/near/near-sdk-rs.git", rev="b8c8589" }
nep21-mintable = { path = "../other-contracts/nep-21" }
